import * as ko from 'knockout';
import {accounts as accountApi} from '../services/accountService';
import {beneficiaries as beneficiaryApi} from '../services/beneficiaryService';
import {perform,recovery,transactions} from '../services/transactionService';
import {Account,Balance,Beneficiary,Transaction} from '../services/types';
import {CreatePaymentDraft,PaymentCategory} from '../services/pendingPayment';
import {paymentAmount,minor,rupees} from '../utils/money';
import {categories,description,label} from '../utils/paymentState';
import {errorText} from '../services/apiError';
import {confirmAction} from '../pageModel';
import {navigate} from '../services/sessionRouteService';
import {refreshLoop} from '../services/refreshLoop';
import {armAudio,chimeForPayment} from '../utils/chime';
import {arcOffset,fluxLetters,formatCountdown,progressKind} from '../utils/protection';
import 'ojs/ojbutton';import 'ojs/ojavatar';import 'ojs/ojtrain';import 'ojs/ojmessages';import 'ojs/ojprogress-circle';import 'ojs/ojdialog';
class SendMoney {
 step=ko.observable('beneficiary');accounts=ko.observableArray<Account>([]);account=ko.observable<Account|null>(null);selectedAccountId=ko.observable('');funds=ko.observable<Balance|null>(null);beneficiaries=ko.observableArray<Beneficiary>([]);selected=ko.observable<Beneficiary|null>(null);
 amount=ko.observable('');purpose=ko.observable('');customerReference=ko.observable('');category=ko.observable('');categories=categories;
 loading=ko.observable(false);busy=ko.observable(false);refreshing=ko.observable(false);error=ko.observable('');notice=ko.observable('');fundsError=ko.observable('');paymentError=ko.observable('');amountError=ko.observable('');purposeError=ko.observable('');attemptLocked=ko.observable(false);result=ko.observable<Transaction|null>(null);cancelOpen=ko.observable(false);stale=ko.observable(false);now=ko.observable(performance.now());processing=ko.observable(0);
 private alive=true;private epoch=0;private observed=0;private stop?:()=>void;private tick?:ReturnType<typeof setInterval>;private draft?:CreatePaymentDraft;
 private sheetSubscription:ko.Subscription;
 constructor(private context:any={}){this.sheetSubscription=this.step.subscribe(()=>requestAnimationFrame(()=>this.syncSheet()));}
 private syncSheet(){const sheet=document.getElementById('payment-sheet') as HTMLDialogElement|null;if(!sheet||typeof sheet.showModal!=='function')return;if(this.sheetOpen()){if(!sheet.open)sheet.showModal();(sheet.querySelector('input:not([disabled]),button:not([disabled])') as HTMLElement|null)?.focus();}else if(sheet.open)sheet.close();}
 cancelSheet=()=>{void this.back();return false;};
 accountOption=(a:Account)=>a.accountType+' '+a.maskedAccountNumber+' · '+a.status;mask=(v:string)=>v||'Unavailable';money=rupees;initials=(v:string)=>(v||'?')[0].toUpperCase();isNew=(v:string)=>Date.now()-Date.parse(v)<86400000;added=(v:string)=>'Added '+new Date(v).toLocaleDateString('en-IN');
 highValue=ko.pureComputed(()=>{try{return minor(paymentAmount(this.amount()))>10000000n;}catch{return false;}});
 remaining=ko.pureComputed(()=>this.result()?.state==='PROTECTED'&&typeof this.result()?.protectionRemainingMillis==='number'?Math.max(0,this.result()!.protectionRemainingMillis!-(this.now()-this.observed))/1000:NaN);
 canCancel=ko.pureComputed(()=>!this.busy()&&!this.stale()&&!!this.result()?.canCancel&&!this.attemptLocked()&&(this.result()?.state!=='PROTECTED'||this.remaining()>0));
 canAuthorize=ko.pureComputed(()=>this.result()?.state==='CREATED'&&!this.busy()&&!this.stale()&&!this.attemptLocked());
 resultTitle=ko.pureComputed(()=>this.result()?label(this.result()!.state):'Checking payment');resultDescription=ko.pureComputed(()=>description(this.result()?.state||''));countdown=ko.pureComputed(()=>Number.isFinite(this.remaining())?formatCountdown(this.remaining())+' remaining':'Refresh for the current protection time.');
 countdownClock=ko.pureComputed(()=>formatCountdown(this.remaining()));isProtected=ko.pureComputed(()=>this.result()?.state==='PROTECTED');isSettling=ko.pureComputed(()=>this.isProtected()&&this.remaining()===0);
 isHold=ko.pureComputed(()=>['VERIFICATION_REQUIRED','PENDING_RISK_REVIEW'].includes(this.result()?.state||''));needsCall=ko.pureComputed(()=>this.result()?.state==='VERIFICATION_REQUIRED');isSettled=ko.pureComputed(()=>this.result()?.state==='SETTLED');isCancelled=ko.pureComputed(()=>this.result()?.state==='CANCELLED');
 reasons=ko.pureComputed(()=>this.result()?.riskExplanation?[this.result()!.riskExplanation!]:[]);showReasons=ko.pureComputed(()=>this.reasons().length>0);statusText=ko.pureComputed(()=>label(this.result()?.state||'CREATED'));pauseLabel=ko.pureComputed(()=>this.result()?.riskTier?label(this.result()!.riskTier!):'Awaiting authorization');riskBadge=ko.pureComputed(()=>this.result()?.riskTier?label(this.result()!.riskTier!)+' risk':'Instruction saved');
 riskTone=ko.pureComputed(()=>this.result()?.riskTier==='VERY_HIGH'?'risk-red':this.result()?.riskTier==='HIGH'?'risk-orange':this.result()?.riskTier==='MEDIUM'?'risk-amber':'risk-neutral');
 progressValue=ko.pureComputed(()=>this.isProtected()&&Number.isFinite(this.remaining())&&this.result()?.protectionSeconds?Math.max(0,Math.min(100,100-this.remaining()/this.result()!.protectionSeconds*100)):0);
 fluxChars=ko.pureComputed(()=>fluxLetters(this.isProtected()?'protected':this.busy()?'checking':'ready'));arcOffset=ko.pureComputed(()=>arcOffset(this.progressValue()));fluxPercent=ko.pureComputed(()=>this.progressValue()+'%');showProcessFlux=ko.pureComputed(()=>this.busy()&&!this.result());sheetKind=ko.pureComputed(()=>progressKind(this.result(),this.showProcessFlux()));
 longTicks=ko.pureComputed(()=>Array.from({length:12},(_,i)=>(i+1)*100/12<=this.progressValue()));trainSteps=[{id:'beneficiary',label:'Recipient'},{id:'details',label:'Amount'},{id:'review',label:'Review'},{id:'result',label:'Status'}];trainStep=this.step;payPips=ko.pureComputed(()=>[true,this.step()==='review'||this.step()==='result',this.step()==='result']);
 sheetOpen=ko.pureComputed(()=>this.step()!=='beneficiary');canLeave=ko.pureComputed(()=>this.step()==='result'&&!this.busy()&&!this.attemptLocked());canContinue=ko.pureComputed(()=>!!this.selected()&&this.account()?.status==='ACTIVE'&&!!this.funds()&&!this.loading()&&!this.busy()&&!this.attemptLocked());cannotContinue=ko.pureComputed(()=>!this.canContinue());
 paymentMessages=ko.pureComputed(()=>this.paymentError()?[{severity:'error',summary:this.paymentError()}]:[]);quickAmounts=['500','1000','2000','5000'];amountSize=ko.pureComputed(()=>Math.min(16,Math.max(1,this.amount().length)));amountLong=ko.pureComputed(()=>this.amount().length>8);amountPreview=ko.pureComputed(()=>{try{return rupees(paymentAmount(this.amount()));}catch{return '';}});amountMessage=ko.pureComputed(()=>this.amountError());amountReady=ko.pureComputed(()=>{try{paymentAmount(this.amount());return true;}catch{return false;}});
 parametersChanged(p:any){if(this.result()){this.step('result');return;}if(this.attemptLocked())return;const step=p.step;this.step(step==='review'&&this.draft?'review':step==='details'&&this.selected()?'details':'beneficiary');}
 private syncRecovery(){try{const saved=recovery();this.attemptLocked(saved.status!=='empty');if(saved.status!=='empty')this.paymentError('A previous operation needs confirmation. Recover it in Transactions before starting a replacement.');}catch(e){this.attemptLocked(true);this.paymentError(errorText(e));}}
 load=async()=>{if(this.loading())return;this.loading(true);this.error('');try{const [a,b]=await Promise.all([accountApi.list(),beneficiaryApi.list()]);if(!this.alive)return;this.accounts(a);this.beneficiaries(b.filter(x=>x.status==='ACTIVE'));this.selectedAccountId((a.find(x=>x.accountId===this.selectedAccountId())||a.find(x=>x.status==='ACTIVE')||a[0])?.accountId||'');await this.selectAccount();this.syncRecovery();if(!a.length)this.error('No account is linked to your profile yet.');const id=new URLSearchParams(location.search).get('transactionId');if(id){this.accept(await transactions.get(id));this.step('result');}const recipient=new URLSearchParams(location.search).get('beneficiaryId');if(recipient)this.selected(this.beneficiaries().find(x=>x.beneficiaryId===recipient)||null);}catch(e){if(this.alive)this.error(errorText(e));}finally{if(this.alive)this.loading(false);}};
 selectAccount=async()=>{if(this.result())return;this.account(this.accounts().find(a=>a.accountId===this.selectedAccountId())||null);this.draft=undefined;await this.refreshFunds();};
 refreshFunds=async()=>{const id=this.account()?.accountId,n=++this.epoch;this.funds(null);this.fundsError('');if(!id)return;try{const b=await accountApi.balance(id);if(this.alive&&n===this.epoch)this.funds(b);}catch(e){if(this.alive&&n===this.epoch)this.fundsError(errorText(e));}};
 pick=(b:Beneficiary)=>{if(this.busy()||this.attemptLocked()||this.step()!=='beneficiary')return;this.selected(b);void this.next();};useAmount=(v:string)=>{if(!this.busy()){this.amount(v);this.amountError('');}};
 private async go(step:string){this.step(step);if(this.context.router)await this.context.router.go({path:'send-money',params:{step}});}
 next=async()=>{if(this.canContinue())await this.go('details');};
 back=async()=>{if(this.busy()||this.attemptLocked())return;if(this.result()){await this.leave();return;}await this.go(this.step()==='review'?'details':'beneficiary');};
 continueDetails=async()=>{if(this.busy()||this.attemptLocked())return;this.busy(true);this.amountError('');this.purposeError('');try{
 const amount=paymentAmount(this.amount());if(!this.account()||!this.selected())throw Error('Select an account and beneficiary.');
 await this.refreshFunds();if(!this.funds())throw Error('Refresh available funds before continuing.');if(minor(amount)>minor(this.funds()!.availableBalance))throw Error('Amount exceeds available balance.');
 const purpose=this.purpose().trim(),category=this.highValue()?this.category():undefined;
 if(this.highValue()&&!categories.some(c=>c.value===category))throw Error('Choose a category above ₹1,00,000.');if(purpose.length>(category==='OTHERS'?140:280)||(category==='OTHERS'&&!purpose))throw Error('Others requires a purpose of 1–140 characters. Other purposes allow up to 280.');if(this.customerReference().trim().length>100)throw Error('Customer reference allows up to 100 characters.');
 this.draft=Object.freeze({sourceAccountId:this.account()!.accountId,beneficiaryId:this.selected()!.beneficiaryId,amount,...(purpose?{purpose}:{}),...(this.customerReference().trim()?{customerReference:this.customerReference().trim()}:{}),...(category?{category:category as PaymentCategory}:{})});await this.go('review');
 }catch(e){this.amountError(errorText(e));}finally{if(this.alive)this.busy(false);}};
 private accept(tx:Transaction){if(!this.alive)return;this.observed=performance.now();this.now(this.observed);this.result(tx);this.stale(false);chimeForPayment(tx);}
 confirm=async()=>{if(this.busy()||!this.draft)return;this.busy(true);this.paymentError('');armAudio();try{const state=recovery();if(state.status!=='empty')throw Error('Recover the previous operation in Transactions before creating a payment.');const tx=await perform<Transaction>({operation:'CREATE',payload:this.draft});this.accept(tx);await this.go('result');history.replaceState(null,'',location.pathname+'?transactionId='+tx.transactionId);await this.refreshResult();}catch(e){if(this.alive)this.paymentError(errorText(e));}finally{this.syncRecovery();if(this.alive)this.busy(false);}};
 authorize=async()=>{const id=this.result()?.transactionId;if(!this.canAuthorize()||!await confirmAction('Confirm and authorize?',this.money(this.result()!.amount)+' to '+this.result()!.beneficiaryName+'. SafePay will assess risk and may reserve funds.','Authorize payment'))return;if(this.alive&&this.result()?.transactionId===id)await this.mutate('AUTHORIZE');};
 cancelPayment=async()=>{const id=this.result()?.transactionId;if(!this.canCancel()||!await confirmAction('Cancel this payment?','The server checks the current state and deadline before releasing any reservation.','Cancel payment',true))return;if(this.alive&&this.result()?.transactionId===id)await this.mutate('CANCEL');};
 requestCancel=this.cancelPayment;closeCancel=()=>this.cancelOpen(false);confirmCancel=this.cancelPayment;
 private async mutate(operation:'AUTHORIZE'|'CANCEL'){const tx=this.result();if(!tx||this.busy())return;this.busy(true);this.paymentError('');try{await perform<Transaction>(operation==='AUTHORIZE'?{operation,transactionId:tx.transactionId,payload:{confirmed:true}}:{operation,transactionId:tx.transactionId});}catch(e){if(this.alive)this.paymentError(errorText(e));}finally{await this.refreshResult();this.syncRecovery();if(this.alive)this.busy(false);}}
 refreshResult=async()=>{const id=this.result()?.transactionId;if(!id||this.refreshing())return;this.refreshing(true);try{this.accept(await transactions.get(id));}catch(e){if(this.alive){this.stale(true);this.paymentError(errorText(e));}}finally{if(this.alive)this.refreshing(false);}};
 openPayment=()=>{const tx=this.result();navigate('transactions',tx?{transactionId:tx.transactionId}:{});};startCall=this.openPayment;
 leave=async()=>{if(!this.canLeave())return;this.result(null);this.draft=undefined;this.amount('');this.purpose('');this.category('');this.customerReference('');this.selected(null);await this.go('beneficiary');history.replaceState(null,'','/send-money/beneficiary');await this.refreshFunds();};
 connected(){document.title='Send Money | SafePay';void this.load();this.tick=setInterval(()=>this.now(performance.now()),250);this.stop=refreshLoop(async()=>{if(this.result()&&!this.busy()&&!['SETTLED','CANCELLED','FAILED'].includes(this.result()!.state))await this.refreshResult();},3000);}
 disconnected(){this.sheetSubscription.dispose();const sheet=document.getElementById('payment-sheet') as HTMLDialogElement|null;if(sheet?.open)sheet.close();this.alive=false;this.epoch++;this.stop?.();if(this.tick)clearInterval(this.tick);}
}
export = SendMoney;
