import * as ko from "knockout";
import { Beneficiary } from "../services/beneficiaryService";
import { Account, PaymentTransaction } from "../services/types";
import "ojs/ojprogress-circle";
import "ojs/ojdialog";
import "ojs/ojbutton";
import "ojs/ojtrain";
import "ojs/ojinputtext";
import "ojs/ojavatar";
import "ojs/ojmessages";
interface FlowRouter {
    go(route: {
        path: string;
        params?: {
            step: string;
        };
    }): Promise<unknown>;
}
declare class SendMoneyViewModel {
    private context;
    step: ko.Observable<string>;
    beneficiaries: ko.ObservableArray<Beneficiary>;
    selected: ko.Observable<Beneficiary | null>;
    accounts: ko.ObservableArray<Account>;
    selectedAccountId: ko.Observable<number | null>;
    accountOption: (a: Account) => string;
    private allBeneficiaries;
    account: ko.Observable<Account | null>;
    amount: ko.Observable<string>;
    purpose: ko.Observable<string>;
    amountError: ko.Observable<string>;
    purposeError: ko.Observable<string>;
    error: ko.Observable<string>;
    notice: ko.Observable<string>;
    loading: ko.Observable<boolean>;
    busy: ko.Observable<boolean>;
    paymentError: ko.Observable<string>;
    result: ko.Observable<PaymentTransaction | null>;
    attemptLocked: ko.Observable<boolean>;
    refreshing: ko.Observable<boolean>;
    cancelOpen: ko.Observable<boolean>;
    now: ko.Observable<number>;
    processing: ko.Observable<number>;
    trainSteps: {
        id: string;
        label: string;
    }[];
    paymentMessages: ko.PureComputed<{
        severity: "error";
        summary: string;
        autoTimeout: number;
    }[]>;
    trainStep: ko.PureComputed<string>;
    payPips: ko.PureComputed<boolean[]>;
    private attempt?;
    private cancelKey?;
    private timer?;
    private processTimer?;
    private lastPoll;
    remaining: ko.PureComputed<number>;
    canCancel: ko.PureComputed<boolean>;
    resultTitle: ko.PureComputed<string>;
    countdown: ko.PureComputed<string>;
    countdownClock: ko.PureComputed<string>;
    progressValue: ko.PureComputed<number>;
    reasons: ko.PureComputed<string[]>;
    statusText: ko.PureComputed<string>;
    pauseLabel: ko.PureComputed<string>;
    riskBadge: ko.PureComputed<string>;
    amountSize: ko.PureComputed<number>;
    isProtected: ko.PureComputed<boolean>;
    isSettling: ko.PureComputed<boolean>;
    isHold: ko.PureComputed<boolean>;
    needsCall: ko.PureComputed<boolean>;
    isSettled: ko.PureComputed<boolean>;
    isCancelled: ko.PureComputed<boolean>;
    showReasons: ko.PureComputed<boolean>;
    riskTone: ko.PureComputed<string>;
    fluxPhase: ko.PureComputed<string>;
    fluxChars: ko.PureComputed<{
        char: string;
        delay: string;
    }[]>;
    arcOffset: ko.PureComputed<number>;
    fluxPercent: ko.PureComputed<string>;
    showProcessFlux: ko.PureComputed<boolean>;
    private alive;
    private initialStep;
    canContinue: ko.PureComputed<boolean>;
    cannotContinue: ko.PureComputed<boolean>;
    sheetOpen: ko.PureComputed<boolean>;
    canLeave: ko.PureComputed<boolean>;
    sheetKind: ko.PureComputed<import("../utils/protection").ProgressKind>;
    longTicks: ko.PureComputed<boolean[]>;
    quickAmounts: string[];
    mask: (value: string) => string;
    money: (value: number) => string;
    amountPreview: ko.PureComputed<string>;
    amountLong: ko.PureComputed<boolean>;
    amountIssue: ko.PureComputed<string>;
    amountMessage: ko.PureComputed<string>;
    amountReady: ko.PureComputed<boolean>;
    isNew: (date: string) => boolean;
    added: (date: string) => string;
    initials: (name: string) => string;
    constructor(context: {
        router: FlowRouter;
        params?: {
            step?: string;
        };
    });
    parametersChanged(params: {
        step?: string;
    }): void;
    load: () => Promise<void>;
    selectAccount: () => void;
    choose: (beneficiary: Beneficiary) => void;
    pick: (beneficiary: Beneficiary) => void;
    useAmount: (value: string) => void;
    next: () => Promise<void>;
    back: () => Promise<void>;
    leave: () => Promise<void>;
    private amountProblem;
    private validateDetails;
    continueDetails: () => Promise<void>;
    private showPaymentError;
    private acceptResult;
    confirm: () => Promise<void>;
    private startProcessFlux;
    private stopProcessFlux;
    refreshResult: () => Promise<void>;
    requestCancel: () => void;
    closeCancel: () => void;
    confirmCancel: () => Promise<void>;
    cancelPayment: () => Promise<void>;
    private startPolling;
    private stopPolling;
    connected(): void;
    disconnected(): void;
}
export = SendMoneyViewModel;
