package com.ofss.beans;

public enum IdempotencyOperation {
    TRANSACTION_CREATE,
    TRANSACTION_AUTHORIZE,
    TRANSACTION_CANCEL,
    TRANSACTION_RELEASE,
    TRANSACTION_SETTLE,
    OTP_ISSUE,
    OTP_VERIFY,
    OTP_RESEND,
    RISK_REVIEW_APPROVE,
    RISK_REVIEW_REJECT,
    RISK_REVIEW_REQUEST_VERIFICATION,
    RISK_REVIEW_ADD_NOTE
}
