package com.ofss.beans;

public enum NotificationType {
    PAYMENT_PROTECTED,
    PAYMENT_RELEASED,
    PAYMENT_CANCELLED,
    OTP_REQUIRED,
    OTP_VERIFIED,
    RISK_REVIEW_PENDING,
    RISK_REVIEW_APPROVED,
    RISK_REVIEW_REJECTED,
    PAYMENT_SETTLED,
    PAYMENT_FAILED
}
