#spring.application.name=SafePay
#server.port=${PORT:8080}
# Database settings are selected by application-local.yml or application-oracle.yml.
spring.application.name=SafePay

server.port=8080

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.username=SAFEPAY_TEAM
spring.datasource.password=SAFEPAY

# ===============================
# === Hibernate JPA Settings ====
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.halt_on_error=true
spring.jpa.show-sql=true