#spring.application.name=SafePay
#server.port=${PORT:8080}
# Database settings are selected by application-local.yml or application-oracle.yml.
spring.application.name=SafePay

server.port=8080

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:FREE
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.username=SYSTEM
spring.datasource.password=Sky123

# ===============================
# === Hibernate JPA Settings ====
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.halt_on_error=true
spring.jpa.show-sql=true