const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('fs'),path=require('path'),vm=require('vm'),ts=require('typescript'),ko=require('knockout');
const root=path.join(__dirname,'../src/ts');
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','X-CSRF-TOKEN':'test-csrf'}});
function fixture(overrides={},replies=[]){
 const cache=new Map(),calls=[],redirects=[],profile=ko.observable(null);let keys=0;
 const context=vm.createContext({URL,URLSearchParams,Headers,Response,TextEncoder,Date,Intl,BigInt,
  crypto:{randomUUID:()=>`integration-key-${++keys}`},setInterval:()=>1,clearInterval:()=>{},setTimeout:()=>1,clearTimeout:()=>{},
  document:{hidden:false,title:'',getElementById:()=>({focus(){}})},window:{location:{replace:p=>redirects.push(p)}},
  fetch:async(url,options)=>{calls.push({url,...options});const reply=replies.shift();if(reply instanceof Error)throw reply;if(!reply)throw Error('Unexpected request '+url);return reply;}});
 function load(name){name=name.replace(/\\/g,'/').replace(/\.ts$/,'');if(overrides[name])return overrides[name];
  if(name==='knockout')return ko;if(name.startsWith('ojs/'))return {};
  if(name==='appController')return {default:{profile}};if(name==='accUtils')return {announce(){}};
  if(name==='utils/chime')return {armAudio(){},chimeForPayment(){},chimeIfSettled(){},rememberSettled(){}};
  if(cache.has(name))return cache.get(name).exports;const module={exports:{}};cache.set(name,module);
  const code=ts.transpileModule(fs.readFileSync(path.join(root,name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2021}}).outputText;
  vm.runInContext('(function(require,module,exports){'+code+'\n})',context)(p=>load(p.startsWith('.')?path.posix.normalize(path.posix.join(path.posix.dirname(name),p)):p),module,module.exports);return module.exports;
 }
 return {load,calls,redirects};
}
const account={accountId:10,accountNumber:'0000010',accountType:'SAVINGS',status:'ACTIVE',balance:2000000};
const hold={transactionId:50,transactionRef:'SYNTHETIC',amount:120000,customerName:'Test',beneficiaryName:'Recipient',createdAt:'2026-09-17T12:00:00',riskReason:'Amount above INR 100000',decision:'PENDING'};
test('former demo credentials are sent to the real login endpoint',async()=>{const f=fixture({},[json({role:'CUSTOMER'})]);await f.load('services/authService').authService.login({email:'anika.demo@safepay.test',password:'DemoPay@123'});assert.equal(f.calls.length,1);assert.match(f.calls[0].url,/\/api\/auth\/login$/);});
test('registration sends only backend fields; no PIN, KYC, or caller-selected role',async()=>{const f=fixture({},[json({userId:1})]);await f.load('services/authService').authService.register({name:'Test',email:'ui@example.test',phone:'9876543210',password:'OnlyTest#2026',pin:'123456',role:'ADMIN'});assert.deepEqual(Object.keys(JSON.parse(f.calls[0].body)).sort(),['email','name','password','phone']);});
test('beneficiary list and create explicitly select the source account',async()=>{const f=fixture({},[json([]),json({beneficiaryId:1})]);const s=f.load('services/beneficiaryService').beneficiaryService;await s.list(11,true);await s.create({accountId:11,beneficiaryName:'Payee',bankAccountNumber:'00123456',ifsc:'HDFC0001234'});assert.match(f.calls[0].url,/accountId=11&includeInactive=true$/);assert.equal(JSON.parse(f.calls[1].body).accountId,11);});
test('account list uses the existing plural endpoint',async()=>{const f=fixture({},[json([account,{...account,accountId:11}])]);assert.equal((await f.load('services/accountService').accountService.list()).length,2);assert.match(f.calls[0].url,/\/api\/accounts$/);});
test('admin approval uses the actual route, admin CSRF and a stable operation key',async()=>{const f=fixture({},[json({}),json({state:'SETTLED'})]);const s=f.load('services/adminHoldService').adminHoldService;await s.approve(50,'stable-approval');assert.match(f.calls[0].url,/\/api\/admin\/reports\/transactions\/summary$/);assert.match(f.calls[1].url,/\/api\/admin\/transactions\/50\/approve$/);assert.equal(f.calls[1].headers.get('Idempotency-Key'),'stable-approval');assert.equal(f.calls[1].headers.get('X-CSRF-TOKEN'),'test-csrf');assert.equal(s.sendOtp,undefined);assert.equal(s.reject,undefined);});
test('pending holds come from the actual backend queue',async()=>{const f=fixture({},[json([{...hold,amount:'120000.00'}])]);const rows=await f.load('services/adminHoldService').adminHoldService.list();assert.equal(rows[0].amount,120000);assert.match(f.calls[0].url,/\/api\/admin\/transactions\/hard-holds$/);});
test('no customer verification endpoint is exposed by the live payment service',()=>{const s=fixture().load('services/transactionService').transactionService;assert.equal(s.verifyHold,undefined);assert.equal(s.requestVerification,undefined);assert.equal(s.verify,undefined);});
test('countdown uses server remaining milliseconds even without timezone suffix',()=>{const f=fixture(),s=f.load('services/transactionService'),p=f.load('utils/protection');const tx=s.receivedPayment({state:'PROTECTED',canCancel:true,protectionRemainingMillis:10000,protectionExpiresAt:'2026-09-17T12:00:00'},1000);assert.equal(p.remainingFor(tx,6000),5);assert.equal(p.canCancelPayment(tx,6000),true);assert.equal(p.canCancelPayment(tx,12000),false);assert.equal(p.canCancelPayment({...tx,canCancel:false},6000),false);});
function holdsFixture(approve){const calls=[];const f=fixture({'services/adminHoldService':{adminHoldService:{list:async()=>[hold],approve:async(...args)=>{calls.push(args);return approve?approve():{state:'SETTLED'};}}}});const Model=f.load('viewModels/adminHolds').AdminHoldsModel;return {...f,model:new Model(),approvalCalls:calls};}
test('admin must explicitly confirm before approval; customer OTP is never required',async()=>{const f=holdsFixture();await f.model.load();f.model.select(hold);await f.model.approve();assert.equal(f.approvalCalls.length,0);f.model.confirmed(true);await f.model.approve();assert.equal(f.approvalCalls.length,1);assert.equal(f.model.pending().length,0);assert.match(f.model.notice(),/approved and settled/);f.model.disconnected();});
test('ambiguous approval retains the same key for an explicit retry',async()=>{let n=0;const f=holdsFixture(()=>{if(!n++)throw Error('connection lost');return {state:'SETTLED'};});await f.model.load();f.model.select(hold);f.model.confirmed(true);await f.model.approve();assert.equal(f.model.pending().length,1);await f.model.approve();assert.equal(f.approvalCalls[0][1],f.approvalCalls[1][1]);f.model.disconnected();});
test('approval double click is ignored and a late response cannot repopulate a closed view',async()=>{let finish;const f=holdsFixture(()=>new Promise(r=>finish=r));await f.model.load();f.model.select(hold);f.model.confirmed(true);const pending=f.model.approve();await f.model.approve();assert.equal(f.approvalCalls.length,1);f.model.disconnected();finish({state:'SETTLED'});await pending;assert.equal(f.model.selected(),null);assert.equal(f.model.notice(),'');});
test('admin account browsing uses only GET requests and has no credit action',async()=>{const accounts=[{...account,balance:'2000000.00'},{...account,accountId:11,balance:'125000.00'}];const f=fixture({},[json([{userId:1,name:'Test'}]),json(accounts)]);const service=f.load('services/adminUserService').adminUserService;const Model=f.load('viewModels/adminUsers').AdminUsersModel,m=new Model();await m.load();await m.select(m.users()[0]);m.selectedAccountId(11);m.selectAccount();assert.equal(m.account().accountId,11);assert.equal(m.account().balance,'125000.00');assert.equal(service.credit,undefined);assert.equal(m.submit,undefined);assert.equal(m.retry,undefined);assert.equal(f.calls.length,2);assert.ok(f.calls.every(c=>c.method==='GET'));assert.match(f.calls[1].url,/\/api\/admin\/users\/1\/accounts$/);m.disconnected();assert.equal(m.accounts().length,0);});
test('changing the source account clears the recipient and isolates each account payees',async()=>{const f=fixture({'services/accountService':{accountService:{list:async()=>[account,{...account,accountId:11}]}},'services/beneficiaryService':{beneficiaryService:{list:async()=>[{beneficiaryId:1,accountId:10,status:'ACTIVE'},{beneficiaryId:2,accountId:11,status:'ACTIVE'}]}}});const Model=f.load('viewModels/send-money'),m=new Model({router:{go:async()=>{}}});await m.load();assert.equal(m.beneficiaries()[0].beneficiaryId,1);m.choose(m.beneficiaries()[0]);m.selectedAccountId(11);m.selectAccount();assert.equal(m.selected(),null);assert.equal(m.beneficiaries()[0].beneficiaryId,2);m.disconnected();});
test('disconnect ignores a late transaction response',async()=>{let finish;const f=fixture({'services/transactionService':{transactionService:{list:()=>new Promise(r=>finish=r)}}});const Model=f.load('viewModels/transactions'),m=new Model();const pending=m.load();m.disconnected();finish([{transactionId:7,state:'SETTLED'}]);await pending;assert.equal(m.transactions().length,0);});
test('registration completes real contact/password steps and clears secrets',async()=>{const calls=[];const f=fixture({'services/authService':{authService:{register:async body=>calls.push(body)}}});const Model=f.load('viewModels/register'),m=new Model();m.phone('9876543210');await m.next();m.name('Synthetic User');m.email('synthetic@example.test');await m.next();m.password('OnlyTest#2026');m.confirmPassword('OnlyTest#2026');await m.next();assert.equal(calls.length,1);assert.equal(m.step(),'success');assert.equal(m.password(),'');assert.equal('pin' in calls[0],false);});
test('registration mismatched password makes no API request',async()=>{let n=0;const f=fixture({'services/authService':{authService:{register:async()=>n++}}});const Model=f.load('viewModels/register'),m=new Model();m.phone('9876543210');await m.next();m.name('Test');m.email('test@example.test');await m.next();m.password('OnlyTest#2026');m.confirmPassword('different');await m.next();assert.equal(n,0);assert.match(m.error(),/do not match/);});
test('restored admin logout recovers CSRF from an admin resource without replaying writes',async()=>{const f=fixture({},[json({message:'Access denied'},403),json({totalTransactions:0}),json({message:'Logged out'})]);await f.load('services/authService').authService.logout();assert.equal(f.calls.length,3);assert.match(f.calls[0].url,/\/api\/accounts\/current$/);assert.match(f.calls[1].url,/\/api\/admin\/reports\/transactions\/summary$/);assert.equal(f.calls[2].method,'POST');assert.match(f.calls[2].url,/\/api\/auth\/logout$/);assert.equal(f.calls[2].headers.get('X-CSRF-TOKEN'),'test-csrf');});